# Generated by Django 2.0 on 2020-06-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0010_customuser_noti_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_number',
        ),
    ]
